name: diaryuploader
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  diary_split:
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_calendar_uploader:
  google_sign_in_all_platforms: ^0.0.4
  flutter_dotenv: ^5.1.0

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - secrets.env
